package modelos;

// Generated 07-24-2013 10:35:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeGenero generated by hbm2java
 */
@Entity
@Table(name = "DE_GENERO", schema = "PONCE")
public class DeGenero implements java.io.Serializable {

	private BigDecimal id;
	private String nombre;
	private String descripcion;
	private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

	public DeGenero() {
	}

	public DeGenero(BigDecimal id) {
		this.id = id;
	}

	public DeGenero(BigDecimal id, String nombre, String descripcion,
			Set<Pelicula> peliculas) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.peliculas = peliculas;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 2)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deGenero")
	public Set<Pelicula> getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Set<Pelicula> peliculas) {
		this.peliculas = peliculas;
	}

}
