package modelos;

// Generated 07-24-2013 10:35:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstadisticasId generated by hbm2java
 */
@Embeddable
public class EstadisticasId implements java.io.Serializable {

	private String genero;
	private BigDecimal totalLibros;
	private BigDecimal precioMedio;

	public EstadisticasId() {
	}

	public EstadisticasId(String genero, BigDecimal totalLibros,
			BigDecimal precioMedio) {
		this.genero = genero;
		this.totalLibros = totalLibros;
		this.precioMedio = precioMedio;
	}

	@Column(name = "GENERO", length = 20)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "TOTAL_LIBROS", precision = 22, scale = 0)
	public BigDecimal getTotalLibros() {
		return this.totalLibros;
	}

	public void setTotalLibros(BigDecimal totalLibros) {
		this.totalLibros = totalLibros;
	}

	@Column(name = "PRECIO_MEDIO", precision = 22, scale = 0)
	public BigDecimal getPrecioMedio() {
		return this.precioMedio;
	}

	public void setPrecioMedio(BigDecimal precioMedio) {
		this.precioMedio = precioMedio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadisticasId))
			return false;
		EstadisticasId castOther = (EstadisticasId) other;

		return ((this.getGenero() == castOther.getGenero()) || (this
				.getGenero() != null && castOther.getGenero() != null && this
				.getGenero().equals(castOther.getGenero())))
				&& ((this.getTotalLibros() == castOther.getTotalLibros()) || (this
						.getTotalLibros() != null
						&& castOther.getTotalLibros() != null && this
						.getTotalLibros().equals(castOther.getTotalLibros())))
				&& ((this.getPrecioMedio() == castOther.getPrecioMedio()) || (this
						.getPrecioMedio() != null
						&& castOther.getPrecioMedio() != null && this
						.getPrecioMedio().equals(castOther.getPrecioMedio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGenero() == null ? 0 : this.getGenero().hashCode());
		result = 37
				* result
				+ (getTotalLibros() == null ? 0 : this.getTotalLibros()
						.hashCode());
		result = 37
				* result
				+ (getPrecioMedio() == null ? 0 : this.getPrecioMedio()
						.hashCode());
		return result;
	}

}
