package modelos;

// Generated 07-24-2013 10:35:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Estadisticas generated by hbm2java
 */
@Entity
@Table(name = "ESTADISTICAS", schema = "PONCE")
public class Estadisticas implements java.io.Serializable {

	private EstadisticasId id;

	public Estadisticas() {
	}

	public Estadisticas(EstadisticasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "genero", column = @Column(name = "GENERO", length = 20)),
			@AttributeOverride(name = "totalLibros", column = @Column(name = "TOTAL_LIBROS", precision = 22, scale = 0)),
			@AttributeOverride(name = "precioMedio", column = @Column(name = "PRECIO_MEDIO", precision = 22, scale = 0)) })
	public EstadisticasId getId() {
		return this.id;
	}

	public void setId(EstadisticasId id) {
		this.id = id;
	}

}
