package modelos;

// Generated 07-24-2013 10:35:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Libros generated by hbm2java
 */
@Entity
@Table(name = "LIBROS", schema = "PONCE")
public class Libros implements java.io.Serializable {

	private String isbn;
	private Autores autoresByAutor1;
	private Autores autoresByAutor3;
	private Autores autoresByAutor2;
	private String genero;
	private String titulo;
	private BigDecimal paginas;
	private BigDecimal precio;
	private Short copyright;

	public Libros() {
	}

	public Libros(String isbn) {
		this.isbn = isbn;
	}

	public Libros(String isbn, Autores autoresByAutor1,
			Autores autoresByAutor3, Autores autoresByAutor2, String genero,
			String titulo, BigDecimal paginas, BigDecimal precio,
			Short copyright) {
		this.isbn = isbn;
		this.autoresByAutor1 = autoresByAutor1;
		this.autoresByAutor3 = autoresByAutor3;
		this.autoresByAutor2 = autoresByAutor2;
		this.genero = genero;
		this.titulo = titulo;
		this.paginas = paginas;
		this.precio = precio;
		this.copyright = copyright;
	}

	@Id
	@Column(name = "ISBN", unique = true, nullable = false, length = 10)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTOR1")
	public Autores getAutoresByAutor1() {
		return this.autoresByAutor1;
	}

	public void setAutoresByAutor1(Autores autoresByAutor1) {
		this.autoresByAutor1 = autoresByAutor1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTOR3")
	public Autores getAutoresByAutor3() {
		return this.autoresByAutor3;
	}

	public void setAutoresByAutor3(Autores autoresByAutor3) {
		this.autoresByAutor3 = autoresByAutor3;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTOR2")
	public Autores getAutoresByAutor2() {
		return this.autoresByAutor2;
	}

	public void setAutoresByAutor2(Autores autoresByAutor2) {
		this.autoresByAutor2 = autoresByAutor2;
	}

	@Column(name = "GENERO", length = 20)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "TITULO", length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "PAGINAS", precision = 22, scale = 0)
	public BigDecimal getPaginas() {
		return this.paginas;
	}

	public void setPaginas(BigDecimal paginas) {
		this.paginas = paginas;
	}

	@Column(name = "PRECIO", precision = 22, scale = 0)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "COPYRIGHT", precision = 4, scale = 0)
	public Short getCopyright() {
		return this.copyright;
	}

	public void setCopyright(Short copyright) {
		this.copyright = copyright;
	}

}
