package modelos;

// Generated 07-24-2013 10:35:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name = "PELICULA", schema = "PONCE")
public class Pelicula implements java.io.Serializable {

	private BigDecimal id;
	private DeGenero deGenero;
	private Soporte soporte;
	private String titulo;

	public Pelicula() {
	}

	public Pelicula(BigDecimal id, DeGenero deGenero, Soporte soporte) {
		this.id = id;
		this.deGenero = deGenero;
		this.soporte = soporte;
	}

	public Pelicula(BigDecimal id, DeGenero deGenero, Soporte soporte,
			String titulo) {
		this.id = id;
		this.deGenero = deGenero;
		this.soporte = soporte;
		this.titulo = titulo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERO", nullable = false)
	public DeGenero getDeGenero() {
		return this.deGenero;
	}

	public void setDeGenero(DeGenero deGenero) {
		this.deGenero = deGenero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOPORTE", nullable = false)
	public Soporte getSoporte() {
		return this.soporte;
	}

	public void setSoporte(Soporte soporte) {
		this.soporte = soporte;
	}

	@Column(name = "TITULO", length = 64)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

}
